//! Generated fragments for hand-written pages.
//!
//! Everything here lands in `docs/includes/`, which MkDocs resolves as a
//! snippet root and keeps out of the nav. The distinction from `reference/`:
//! a reference page is the whole document, whereas these are one table each,
//! pulled into a page whose prose is genuinely hand-authored. Each is wrapped
//! in a named snippet section, so the consuming page names the table it wants:
//!
//!     --8<-- "includes/bxp-core-modules.md:table"

const std = @import("std");
const docs = @import("docs");
const module_docs = @import("module_docs");
const bridge_ops = @import("bridge_ops");
const btrace = @import("btrace");
const config = @import("config");

fn open(w: *std.Io.Writer, source: []const u8, name: []const u8) !void {
    try w.print("<!-- GENERATED by tools/zig-doc-gen from {s}. Do not edit. -->\n\n", .{source});
    try w.print("<!-- --8<-- [start:{s}] -->\n\n", .{name});
}

fn close(w: *std.Io.Writer, name: []const u8) !void {
    try w.print("\n<!-- --8<-- [end:{s}] -->\n", .{name});
}

/// bxp-core's module inventory. `origin` is what kept going stale in the
/// hand-written table, so it is rendered from the enum rather than retyped.
pub fn writeModules(w: *std.Io.Writer) !void {
    try open(w, "bxp-core/src/module_docs.zig", "table");
    try w.writeAll("| Module | Source | Responsibility |\n| --- | --- | --- |\n");
    for (module_docs.modules) |m| {
        try w.writeAll("| <code class=\"hl-fn\">");
        try docs.writeEscaped(w, m.name);
        try w.writeAll("</code> | ");
        if (m.origin == .in_tree) {
            try w.writeAll("<code>");
            try docs.writeEscaped(w, m.file);
            try w.writeAll("</code>");
        } else {
            try w.writeAll(m.origin.label());
        }
        if (m.reexport_only) try w.writeAll(" <br>re-export only");
        try w.writeAll(" | ");
        try docs.writeCell(w, m.responsibility);
        try w.writeAll(" |\n");
    }
    try close(w, "table");
}

/// The stateless inspect surface. Held to `inspect.zig`'s public declarations
/// by a comptime check in that file — see the note there.
pub fn writeInspectOps(w: *std.Io.Writer) !void {
    try open(w, "bxp-core/src/module_docs.zig", "table");
    try w.writeAll("| inspect function | Backed by | Purpose |\n| --- | --- | --- |\n");
    for (module_docs.inspect_ops) |op| {
        try w.writeAll("| <code class=\"hl-fn\">");
        try docs.writeEscaped(w, op.name);
        try w.writeAll("</code> | ");
        try docs.writeCell(w, op.backed_by);
        try w.writeAll(" | ");
        try docs.writeCell(w, op.purpose);
        try w.writeAll(" |\n");
    }
    try close(w, "table");
}

/// The bridge's C-ABI surface. Held to the `pub export fn`s by a comptime
/// check in `bxp-gui-bridge/src/main.zig`.
pub fn writeBridgeOps(w: *std.Io.Writer) !void {
    try open(w, "bxp-gui-bridge/src/ops.zig", "table");
    try w.writeAll("| Export | Served | Purpose |\n| --- | --- | --- |\n");
    for (bridge_ops.ops) |op| {
        try w.writeAll("| <code class=\"hl-fn\">");
        try docs.writeEscaped(w, op.name);
        try docs.writeEscaped(w, op.args);
        try w.writeAll("</code> | ");
        try w.writeAll(op.kind.label());
        try w.writeAll(" | ");
        try docs.writeCell(w, op.purpose);
        try w.writeAll(" |\n");
    }
    try close(w, "table");
}

/// The BXTB frame codes. Code and name come from the `FrameType` enum; a new
/// variant without a `frame_docs` entry is a compile error in btrace.zig.
pub fn writeTraceFrames(w: *std.Io.Writer) !void {
    try open(w, "bxp-core/src/btrace.zig", "table");
    try w.writeAll("| Code | Name | Purpose |\n| --- | --- | --- |\n");
    inline for (btrace.frame_docs) |d| {
        try w.print("| <code class=\"hl-num\">0x{X:0>2}</code> | <code class=\"hl-fn\">{s}</code> | ", .{ @intFromEnum(d.t), @tagName(d.t) });
        try docs.writeCell(w, d.purpose);
        try w.writeAll(" |\n");
    }
    try close(w, "table");
}

/// The `csv_*_encoding` value list, for the guide page that teaches the
/// setting. Read out of the same `FieldDoc.enum_values` the config schema
/// renders, so the guide cannot list a code page the loader would reject.
pub fn writeCsvEncodings(w: *std.Io.Writer) !void {
    try open(w, "bxp-core/src/config.zig", "values");
    const key = "csv_input_encoding";
    const values = for (config.BrokerConfig.fields) |f| {
        if (std.mem.eql(u8, f.key, key)) break f.enum_values orelse
            @panic(key ++ " lost its enum_values");
    } else @panic(key ++ " is no longer a BrokerConfig field");

    for (values) |v| {
        try w.writeAll("- <code class=\"hl-str\">");
        try docs.writeEscaped(w, v);
        try w.writeAll("</code>\n");
    }
    try close(w, "values");
}
