//! Central generated-Markdown tool. Imports every Zig `*Doc` catalog and the
//! shared `docs.writeTable` renderer, and emits each generated page under
//! BXP_DOCS_OUT (default ../../docs) by its site-relative path. Most land in
//! `reference/`; the architecture class diagram is rendered straight out of
//! `@typeInfo` and lands next to the pages it belongs with. The Dart
//! `GuiToolDoc` pages are generated separately by tools/dart-doc-gen
//! (language boundary).

const std = @import("std");
const docs = @import("docs");
const cli_docs = @import("cli_docs");
const mcp_tools = @import("tools");
const config = @import("config");
const structs = @import("structs.zig");
const includes = @import("includes.zig");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    const out = init.environ_map.get("BXP_DOCS_OUT") orelse "../../docs";

    // ── bxp-core catalogs (expr functions, date tokens, config schema) ──
    {
        const f = try create(io, out, "reference/expr-functions.md");
        defer f.close(io);
        var buf: [16384]u8 = undefined;
        var fw = f.writer(io, &buf);
        try docs.writeFunctionsMd(&fw.interface);
        try fw.interface.flush();
    }
    {
        const f = try create(io, out, "reference/date-tokens.md");
        defer f.close(io);
        var buf: [8192]u8 = undefined;
        var fw = f.writer(io, &buf);
        try docs.writeDateTokensMd(&fw.interface);
        try fw.interface.flush();
    }
    {
        const f = try create(io, out, "reference/config-schema.md");
        defer f.close(io);
        var buf: [16384]u8 = undefined;
        var fw = f.writer(io, &buf);
        try docs.writeConfigSchemaMd(alloc, &fw.interface);
        try fw.interface.flush();
    }

    // ── bxp-cli catalogs (flags, exit codes) ──
    {
        const f = try create(io, out, "reference/cli-flags.md");
        defer f.close(io);
        var buf: [8192]u8 = undefined;
        var fw = f.writer(io, &buf);
        const w = &fw.interface;
        try w.writeAll(
            \\---
            \\description: "Every bxp-cli command-line flag, its argument and what it does."
            \\---
            \\
            \\# CLI flags
            \\
            \\<!-- GENERATED by tools/zig-doc-gen from cli_docs.flags. Do not edit. -->
            \\
            \\All flags are optional. Without arguments, bxp-cli reads `bxp-cli.json` from the current directory.
            \\
            \\
        );
        try docs.writeTable(w, &cli_docs.flags, &.{
            .{ .head = "Flag", .field = "flag", .hl = "hl-fn" },
            .{ .head = "Argument", .field = "arg", .hl = "hl-type" },
            .{ .head = "Description", .field = "description" },
        });
        try w.flush();
    }
    {
        const f = try create(io, out, "reference/exit-codes.md");
        defer f.close(io);
        var buf: [4096]u8 = undefined;
        var fw = f.writer(io, &buf);
        const w = &fw.interface;
        try w.writeAll(
            \\---
            \\description: "What each bxp-cli process exit code means."
            \\---
            \\
            \\# Exit codes
            \\
            \\<!-- GENERATED by tools/zig-doc-gen from cli_docs.exit_codes. Do not edit. -->
            \\
            \\`bxp-cli` process exit codes.
            \\
            \\
        );
        try docs.writeTable(w, &cli_docs.exit_codes, &.{
            .{ .head = "Code", .field = "code", .hl = "hl-num" },
            .{ .head = "Meaning", .field = "meaning" },
        });
        try w.flush();
    }

    // ── bxp-mcp catalog (agent-callable tools) ──
    {
        const f = try create(io, out, "reference/mcp-tools.md");
        defer f.close(io);
        var buf: [8192]u8 = undefined;
        var fw = f.writer(io, &buf);
        const w = &fw.interface;
        try w.writeAll(
            \\---
            \\description: "The agent-callable tools the bxp-mcp stdio server exposes, and how each one is served."
            \\---
            \\
            \\# MCP tools (bxp-mcp)
            \\
            \\<!-- GENERATED by tools/zig-doc-gen from tools.tool_docs. Do not edit. -->
            \\
            \\Agent-callable tools exposed by the `bxp-mcp` stdio server.
            \\
            \\
        );
        try docs.writeTable(w, &mcp_tools.tool_docs, &.{
            .{ .head = "Tool", .field = "name", .hl = "hl-fn" },
            .{ .head = "Description", .field = "description" },
        });
        // The implementation map, wrapped in a pymdownx-snippets section so
        // `docs/dev/mcp.md` can include exactly this table instead of keeping a
        // hand-written copy of it. Same catalog, one source.
        try w.writeAll(
            \\
            \\## How each tool is served
            \\
            \\Every stateless tool is a direct in-process call into
            \\`bxp-core/src/inspect.zig` — the same core the GUI reaches through
            \\`bxp-gui-bridge`, which is why the third column mostly mirrors the second.
            \\`bxp_simulate` is the exception with no `inspect` entry: a full conversion
            \\is not a stateless op, so it spawns the co-located `bxp-cli` instead. A
            \\dash in the last column means the GUI has no equivalent call.
            \\
            \\<!-- --8<-- [start:impl-map] -->
            \\
        );
        try docs.writeTable(w, &mcp_tools.tool_docs, &.{
            .{ .head = "Tool", .field = "name", .hl = "hl-fn" },
            .{ .head = "inspect call", .field = "inspect_call", .hl = "hl-fn" },
            .{ .head = "bridge op", .field = "bridge_op", .hl = "hl-fn" },
        });
        try w.writeAll("\n<!-- --8<-- [end:impl-map] -->\n");
        try w.flush();
    }

    // ── shipped template library (read from the config, not retyped) ──
    //
    // The one page whose source is a data file rather than a Zig catalog. It
    // used to be a hand-kept table in getting-started/, which is precisely the
    // thing that rots: nothing connected it to the config it described, so a
    // thirteenth template would simply never have appeared.
    {
        const examples_path = "../../resources/console/bxp-cli.examples.json";
        const raw = try std.Io.Dir.cwd().readFileAlloc(io, examples_path, alloc, .limited(4 << 20));
        defer alloc.free(raw);

        var cfg = try config.loadFromBytes(alloc, raw, examples_path, null);
        defer cfg.deinit();

        const f = try create(io, out, "reference/built-in-templates.md");
        defer f.close(io);
        var buf: [8192]u8 = undefined;
        var fw = f.writer(io, &buf);
        const w = &fw.interface;
        try w.writeAll(
            \\---
            \\description: "The conversion templates shipped next to the binary, and what each one converts."
            \\---
            \\
            \\# Built-in templates
            \\
            \\<!-- GENERATED by tools/zig-doc-gen from resources/console/bxp-cli.examples.json. Do not edit. -->
            \\
            \\Every template in the `bxp-cli.examples.json` that ships next to the binary,
            \\with the `description` each one declares.
            \\
            \\<!-- --8<-- [start:table] -->
            \\
            \\| Template ID | Converts |
            \\| --- | --- |
            \\
        );
        for (cfg.brokers.keys()) |id| {
            const b = cfg.brokers.get(id).?;
            try w.writeAll("| <code class=\"hl-fn\">");
            try docs.writeEscaped(w, id);
            try w.writeAll("</code> | ");
            if (b.description.len > 0) try docs.writeEscaped(w, b.description) else try w.writeAll("—");
            try w.writeAll(" |\n");
        }
        try w.writeAll("\n<!-- --8<-- [end:table] -->\n");
        try w.flush();
    }

    // ── architecture (rendered from @typeInfo, not from a catalog) ──
    {
        const f = try create(io, out, "dev/architecture/data-structures.md");
        defer f.close(io);
        var buf: [16384]u8 = undefined;
        var fw = f.writer(io, &buf);
        try structs.write(&fw.interface);
        try fw.interface.flush();
    }

    // ── generated fragments for hand-written pages (docs/includes/) ──
    //
    // One table each, included by name from the page whose prose is genuinely
    // hand-authored. See src/includes.zig for the split against reference/.
    {
        const Frag = struct { path: []const u8, render: *const fn (*std.Io.Writer) anyerror!void };
        const frags = [_]Frag{
            .{ .path = "includes/bxp-core-modules.md", .render = includes.writeModules },
            .{ .path = "includes/inspect-surface.md", .render = includes.writeInspectOps },
            .{ .path = "includes/bridge-ops.md", .render = includes.writeBridgeOps },
            .{ .path = "includes/trace-frames.md", .render = includes.writeTraceFrames },
            .{ .path = "includes/csv-encodings.md", .render = includes.writeCsvEncodings },
        };
        for (frags) |frag| {
            const f = try create(io, out, frag.path);
            defer f.close(io);
            var buf: [16384]u8 = undefined;
            var fw = f.writer(io, &buf);
            try frag.render(&fw.interface);
            try fw.interface.flush();
        }
    }

    std.debug.print("zig-doc-gen: wrote generated pages to {s}/\n", .{out});
}

/// `name` is site-relative (`reference/cli-flags.md`), so the drift guard can
/// generate a whole tree into a scratch dir and diff it against `docs/`.
fn create(io: std.Io, root: []const u8, name: []const u8) !std.Io.File {
    var path_buf: [512]u8 = undefined;
    const path = try std.fmt.bufPrint(&path_buf, "{s}/{s}", .{ root, name });
    if (std.fs.path.dirname(path)) |parent| {
        try std.Io.Dir.cwd().createDirPath(io, parent);
    }
    return std.Io.Dir.cwd().createFile(io, path, .{});
}
