#!/usr/bin/env bash
# Generate the MkDocs documentation site and (default) serve it locally.
#
# The reference pages under docs/reference/ are GENERATED from the in-code
# `*Doc` catalogs by the central tool tools/zig-doc-gen (one binary that imports
# every Zig catalog + the shared docs.writeTable renderer). The narrative pages
# under docs/guide/, docs/getting-started/, etc. are hand-authored.
#
# Usage (from any directory):
#   bash scripts/docs/gen-docs.sh          — regenerate reference pages, build the
#                                            site into site/, then `mkdocs serve`
#   bash scripts/docs/gen-docs.sh --build  — regenerate + build site/, no serve
#   bash scripts/docs/gen-docs.sh --check  — verify committed reference pages match
#                                            a fresh generation + every reference
#                                            page is in the nav; exit 1 + diff
#
# The three Dart-catalog pages (gui-agent-tools.md, gui-shortcuts.md,
# gui-prefs.md) can't be read by the Zig tool (language boundary), so they are
# generated by tools/dart-doc-gen, which runs as a `flutter test` (importing
# bxp_gui links dart:ui). All generated pages — Zig and Dart alike — are covered
# by the --check drift guard below.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MONO_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
DOCS_DIR="$MONO_ROOT/docs"
REF_DIR="$DOCS_DIR/reference"
VENV="$MONO_ROOT/.venv-docs"
MKDOCS="$VENV/bin/mkdocs"

# Every generated page, by its site-relative path. Most are reference tables
# rendered from a `*Doc` catalog; data-structures.md is rendered from
# `@typeInfo` over the live types and therefore sits with the architecture
# pages rather than under reference/.
GENERATED_PAGES=(
  reference/expr-functions.md
  reference/date-tokens.md
  reference/config-schema.md
  reference/built-in-templates.md
  reference/cli-flags.md
  reference/exit-codes.md
  reference/mcp-tools.md
  reference/gui-agent-tools.md
  reference/gui-shortcuts.md
  reference/gui-prefs.md
  dev/architecture/data-structures.md
  includes/bxp-core-modules.md
  includes/inspect-surface.md
  includes/bridge-ops.md
  includes/trace-frames.md
  includes/csv-encodings.md
)

mode="serve"
case "${1:-}" in
  --build) mode="build" ;;
  --check) mode="check" ;;
  "") mode="serve" ;;
  *) echo "unknown argument: $1" >&2; exit 2 ;;
esac

run_zig_gen() {
  local out="$1"
  ( cd "$MONO_ROOT/tools/zig-doc-gen" && zig build run -- "$out" )
}

# The Dart catalog (GuiToolDoc) can't be read by the Zig tool (language boundary)
# and can't run under plain `dart run` (importing bxp_gui links dart:ui), so its
# generator runs as a `flutter test`. Slower (engine startup) but reliable.
run_dart_gen() {
  local out="$1"
  ( cd "$MONO_ROOT/tools/dart-doc-gen" \
      && flutter pub get >/dev/null \
      && BXP_DOCS_OUT="$out" flutter test test/gen_docs_test.dart >/dev/null )
}

# The repository tree and the test-phase table are harvested from file headers
# rather than from a Zig catalog, so they have their own generator. It owns its
# comparison (it writes into docs/includes/ directly), which is why it is not
# part of GENERATED_PAGES above.
run_tree_gen() {
  python3 "$SCRIPT_DIR/gen-trees.py" "$@"
}

if [[ "$mode" == "check" ]]; then
  rc=0
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  run_zig_gen "$tmp" >/dev/null
  run_dart_gen "$tmp"
  run_tree_gen --check || rc=1

  for page in "${GENERATED_PAGES[@]}"; do
    if ! diff -q "$DOCS_DIR/$page" "$tmp/$page" >/dev/null 2>&1; then
      rc=1
      echo "DRIFT: docs/$page is out of sync with its source — run: bash scripts/docs/gen-docs.sh --build"
      diff "$DOCS_DIR/$page" "$tmp/$page" | head -40 || true
    fi
  done

  # nav coverage: every reference page must be listed in mkdocs.yml.
  for f in "$REF_DIR"/*.md; do
    name="reference/$(basename "$f")"
    if ! grep -qF "$name" "$MONO_ROOT/mkdocs.yml"; then
      rc=1
      echo "NAV: $name exists but is not listed in mkdocs.yml nav:"
    fi
  done

  [[ $rc -eq 0 ]] && echo "gen-docs --check: reference pages + nav in sync"
  exit $rc
fi

# serve / build: regenerate in place, then build the site.
run_zig_gen "$DOCS_DIR"
run_dart_gen "$DOCS_DIR"
run_tree_gen

# The docs playground's wasm engine. Not a tracked file (see .gitignore), so a
# fresh checkout has to build it here or every playground on the site reports
# that it could not load the engine. Deliberately NOT part of --check: it is a
# binary artifact, not generated prose, so there is nothing to drift-guard.
bash "$SCRIPT_DIR/gen-wasm-playground.sh"

if [[ ! -x "$MKDOCS" ]]; then
  echo "mkdocs not found at $MKDOCS" >&2
  echo "create the docs venv first:" >&2
  echo "  python3 -m venv $VENV && $VENV/bin/pip install -r $MONO_ROOT/scripts/docs/requirements.txt" >&2
  exit 1
fi

# A venv survives its interpreter being replaced under it — after an OS upgrade
# `bin/python` can point at a newer Python that cannot see the site-packages
# the venv was built with, and mkdocs then reports itself missing while being
# installed. Say so, rather than sending the reader to reinstall a package that
# is already there.
if ! "$MKDOCS" --version >/dev/null 2>&1; then
  echo "$MKDOCS exists but cannot run — most likely the venv was built with a" >&2
  echo "different Python than $VENV/bin/python resolves to today." >&2
  echo "recreate it:" >&2
  echo "  rm -rf $VENV && python3 -m venv $VENV \\" >&2
  echo "    && $VENV/bin/pip install -r $MONO_ROOT/scripts/docs/requirements.txt" >&2
  exit 1
fi

( cd "$MONO_ROOT" && "$MKDOCS" build --strict )

if [[ "$mode" == "serve" ]]; then
  echo "serving docs at http://127.0.0.1:8000 (Ctrl+C to stop)"
  ( cd "$MONO_ROOT" && "$MKDOCS" serve )
fi
