; NSIS installer for BXP Desktop on Windows.
;
; Build with: makensis -DAPPVERSION=0.2.0 -DVERSIONTAG=v0.2.0 \
;             -DSTAGEDIR=path\to\stage bxp-desktop.nsi
;
; Outputs: bxp-desktop-windows-x86_64.exe in OUTDIR. The artifact name is
; version-less so the README can link to a stable GitHub release URL
; (releases/latest/download/bxp-desktop-windows-x86_64.exe); the version
; lives in the release tag and in the NSIS Version property.
; APPVERSION is the bare SemVer string (NSIS Version property);
; VERSIONTAG is the release-tag-shaped string used in install metadata.
;
; The installer is silent-capable via /S — UpdaterService relies on this
; to perform unattended self-updates.
;
; UI: Modern UI 2 (built-in NSIS macro pack). Branding bitmaps live in
; the same directory as this script and are regenerated from
; resources/icons/ via `build-installer-assets.ps1`.

!ifndef APPVERSION
  !define APPVERSION "0.0.0"
!endif
!ifndef VERSIONTAG
  !define VERSIONTAG "${APPVERSION}"
!endif
!ifndef STAGEDIR
  !error "STAGEDIR must be defined (path to staged Flutter Windows release)"
!endif
!ifndef OUTDIR
  !define OUTDIR "."
!endif

; APPNAME is overridable (!ifndef) so the installer-preview harness can build
; a sandboxed "BXP Preview" that writes separate Start-Menu / HKCU keys and
; never collides with a real install. Production builds leave it at "BXP".
!ifndef APPNAME
  !define APPNAME "BXP"
!endif
!define COMPANYNAME "io.github.bxp"
; Plain ASCII hyphen, not em-dash. NSIS processes this script in ANSI
; mode (codepage interpretation depends on the build host) and a UTF-8
; em-dash here renders as three garbage bytes on the Welcome page.
!define DESCRIPTION "Broker eXchange Parser - desktop config editor"
; Per-user install (mirrors the Linux AppImage / macOS ~/Applications model):
; LOCALAPPDATA needs no admin rights, so the silent self-updater's
; non-elevated Process.start can launch setup.exe without hitting
; ERROR_ELEVATION_REQUIRED (the old $PROGRAMFILES64 + RequestExecutionLevel
; admin combo could not elevate via CreateProcess and silently failed).
; Overridable (!ifndef) for the preview harness — a sandbox dir keeps the
; fake install out of the real per-user location. Production uses the default.
!ifndef INSTALLDIR_DEFAULT
  !define INSTALLDIR_DEFAULT "$LOCALAPPDATA\Programs\bxp-gui"
!endif

Name "${APPNAME}"
OutFile "${OUTDIR}\bxp-desktop-windows-x86_64.exe"
InstallDir "${INSTALLDIR_DEFAULT}"
RequestExecutionLevel user
SetCompressor /SOLID lzma

; Blank the bottom-left "Nullsoft Install System vX.Y" branding strip. A single
; space empties the text (NSIS keeps the control but draws nothing). Applies to
; both themes — a shipped installer should not read like a generic Nullsoft wizard.
BrandingText " "

; ── Modern UI 2 ──────────────────────────────────────────────────────────
;
; Reuses Flutter's app_icon.ico (sand-80 source via build-icons.sh) for
; both setup.exe and Uninstall.exe. Branding BMPs are 24-bit BMP3 — MUI2
; cannot render BMPv4/v5 correctly. See `build-installer-assets.ps1` for
; regeneration when the source icon changes.
!include "MUI2.nsh"

!define MUI_ICON   "..\windows\runner\resources\app_icon.ico"
!define MUI_UNICON "..\windows\runner\resources\app_icon.ico"

; Branding bitmaps are overridable so a dark build can pass the -dark variants
; (header-dark.bmp / welcome-dark.bmp) generated by build-installer-assets.ps1 -Dark.
!ifndef HEADER_BITMAP
  !define HEADER_BITMAP  "header.bmp"
!endif
!ifndef WELCOME_BITMAP
  !define WELCOME_BITMAP "welcome.bmp"
!endif

!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP        "${HEADER_BITMAP}"
!define MUI_WELCOMEFINISHPAGE_BITMAP  "${WELCOME_BITMAP}"
; Mirror the branding onto the uninstaller pages — without these the uninstaller
; falls back to the stock light MUI bitmaps (no BXP logo, light welcome strip).
!define MUI_HEADERIMAGE_UNBITMAP      "${HEADER_BITMAP}"
!define MUI_UNWELCOMEFINISHPAGE_BITMAP "${WELCOME_BITMAP}"

; ── Optional dark theme (-DDARK) ─────────────────────────────────────────
; NSIS/MUI2 has no OS-following dark mode. This darkens what the classic Win32
; UI reliably allows: page/control backgrounds + text via MUI_BGCOLOR/
; MUI_TEXTCOLOR and per-control SetCtlColors (see the GUIINIT + page-SHOW
; hooks), plus the title bar via the documented DWM immersive-dark attribute.
; Two things stay system-light by design:
;   * the native Back/Next/Cancel/Browse push buttons (not owner-drawn), and
;   * classic 3D borders / scrollbars (etched by comctl, not via SetCtlColors).
; Darkening those last two needs the *undocumented* Win10 dark-mode opt-in
; (uxtheme SetPreferredAppMode/AllowDarkModeForWindow). It was tried and
; rejected: once the process is in dark mode the themed edit + group-box title
; ignore SetCtlColors and render unreadable dark-on-dark text. Readability wins;
; the group box (a redundant light frame) is hidden instead. Pair with the dark
; branding bitmaps via -DHEADER_BITMAP / -DWELCOME_BITMAP.
!ifdef DARK
  !define MUI_BGCOLOR   "1E1E1E"
  !define MUI_TEXTCOLOR "EDEDED"
  !define MUI_CUSTOMFUNCTION_GUIINIT   BxpDarkGuiInit
  !define MUI_CUSTOMFUNCTION_UNGUIINIT un.BxpDarkGuiInit
!endif

; Tighten the welcome/finish page text — MUI2 defaults read like a
; generic Win 95 Setup wizard otherwise.
!define MUI_WELCOMEPAGE_TITLE   "Install ${APPNAME}"
!define MUI_WELCOMEPAGE_TEXT    "This wizard installs ${APPNAME} ${APPVERSION} on your computer.$\r$\n$\r$\n${DESCRIPTION}.$\r$\n$\r$\nClick Next to continue."
!define MUI_FINISHPAGE_TITLE    "${APPNAME} installed"
!define MUI_FINISHPAGE_TEXT     "${APPNAME} ${APPVERSION} has been installed on your computer.$\r$\n$\r$\nClick Finish to close the wizard."
!define MUI_FINISHPAGE_RUN      "$INSTDIR\bxp-gui.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Run ${APPNAME} now"

; The Welcome/Finish pages are darkened by MUI_BGCOLOR/MUI_TEXTCOLOR alone.
; The interior pages (Directory, InstFiles) draw a system-light dialog body
; that those defines don't reach — a SHOW hook recolors the inner dialog +
; its child controls. Define the hook per page (MUI consumes the define).
!insertmacro MUI_PAGE_WELCOME
!ifdef DARK
  !define MUI_PAGE_CUSTOMFUNCTION_SHOW BxpDarkPage
!endif
!insertmacro MUI_PAGE_DIRECTORY
!ifdef DARK
  !define MUI_PAGE_CUSTOMFUNCTION_SHOW BxpDarkPage
!endif
!insertmacro MUI_PAGE_INSTFILES
!ifdef DARK
  !define MUI_PAGE_CUSTOMFUNCTION_SHOW BxpDarkPage
!endif
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_WELCOME
!ifdef DARK
  !define MUI_PAGE_CUSTOMFUNCTION_SHOW un.BxpDarkPage
!endif
!insertmacro MUI_UNPAGE_CONFIRM
!ifdef DARK
  !define MUI_PAGE_CUSTOMFUNCTION_SHOW un.BxpDarkPage
!endif
!insertmacro MUI_UNPAGE_INSTFILES
!ifdef DARK
  !define MUI_PAGE_CUSTOMFUNCTION_SHOW un.BxpDarkPage
!endif
!insertmacro MUI_UNPAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

!ifdef DARK
; GUI-init body, shared by the installer (MUI_CUSTOMFUNCTION_GUIINIT) and the
; uninstaller (MUI_CUSTOMFUNCTION_UNGUIINIT). Runs once the wizard window exists.
!macro BXP_DARK_GUIINIT_BODY
    ; Immersive dark title bar (documented DWM attribute). 20 = DWMWA_USE_-
    ; IMMERSIVE_DARK_MODE on Win10 2004+/Win11; 19 on 1809-1909. Calling both is
    ; safe — the inapplicable one is a harmless no-op. This only tints the title
    ; bar; it does not touch control text, so it is unaffected by the readability
    ; trade-off that ruled out the process-wide dark-mode opt-in (see below).
    System::Call 'dwmapi::DwmSetWindowAttribute(p $HWNDPARENT, i 20, *i 1, i 4)'
    System::Call 'dwmapi::DwmSetWindowAttribute(p $HWNDPARENT, i 19, *i 1, i 4)'
    ; Dark background behind the branding band + inner-page margins, then the
    ; wizard window's own direct children (notably the bottom branding strip) so
    ; no system-light rectangle peeks through. Native buttons ignore SetCtlColors
    ; and stay system-light by design.
    SetCtlColors $HWNDPARENT "EDEDED" "1E1E1E"
    Push $0
    Push $1
    StrCpy $0 0
  bxpinit_loop:
    System::Call "user32::FindWindowEx(p $HWNDPARENT, p r0, p 0, p 0) p .r1"
    StrCmp $1 0 bxpinit_done
    SetCtlColors $1 "EDEDED" "1E1E1E"
    StrCpy $0 $1
    Goto bxpinit_loop
  bxpinit_done:
    Pop $1
    Pop $0
    ; Left-align the header subtitle ("Choose the folder…") with the header
    ; title ("Choose Install Location") — MUI indents the subtitle by default.
    ; The header text controls (1037 title, 1038 subtitle) are reused across all
    ; pages, so moving the subtitle once here covers every page. Extend its left
    ; edge to the title's x and keep the right edge (so no text clips).
    Push $0   ; title hwnd
    Push $1   ; subtitle hwnd
    Push $2   ; title screen-left
    Push $3   ; scratch / new width
    Push $4   ; scratch RECT/POINT ptr
    Push $5   ; parent client screen-x
    Push $6   ; parent client screen-y
    Push $7   ; subtitle top -> new y
    Push $8   ; subtitle right -> new x
    Push $9   ; subtitle bottom -> new height
    GetDlgItem $0 $HWNDPARENT 1037
    GetDlgItem $1 $HWNDPARENT 1038
    StrCmp $0 0 bxpalign_done
    StrCmp $1 0 bxpalign_done
    System::Call "*(i 0, i 0) p .r4"               ; POINT {0,0}
    System::Call "user32::ClientToScreen(p $HWNDPARENT, p r4)"
    System::Call "*$4(i .r5, i .r6)"               ; parent client origin (screen)
    System::Call "user32::GetWindowRect(p r0, p r4)"
    System::Call "*$4(i .r2, i, i, i)"             ; $2 = title screen-left
    System::Call "user32::GetWindowRect(p r1, p r4)"
    System::Call "*$4(i, i .r7, i .r8, i .r9)"     ; $7 top  $8 right  $9 bottom
    System::Free $4
    IntOp $3 $8 - $2                               ; new width  = subRight - titleLeft
    IntOp $9 $9 - $7                               ; new height = subBottom - subTop
    IntOp $8 $2 - $5                               ; new x (client) = titleLeft - origin
    IntOp $7 $7 - $6                               ; new y (client) = subTop  - origin
    System::Call "user32::MoveWindow(p r1, i r8, i r7, i r3, i r9, i 1)"
  bxpalign_done:
    Pop $9
    Pop $8
    Pop $7
    Pop $6
    Pop $5
    Pop $4
    Pop $3
    Pop $2
    Pop $1
    Pop $0
!macroend

Function BxpDarkGuiInit
    !insertmacro BXP_DARK_GUIINIT_BODY
FunctionEnd

Function un.BxpDarkGuiInit
    !insertmacro BXP_DARK_GUIINIT_BODY
FunctionEnd

; Recolor the current page's interior. MUI_BGCOLOR doesn't reach the inner
; dialog body or its controls, so the page centre paints system-light. We grab
; the active inner dialog (the #32770 child of the wizard window), give it a
; dark background brush, then walk its child controls. Most controls (static
; labels, the path edit, the details listbox) just take a dark SetCtlColors
; brush. BUTTON-class controls are special: the visual-styles theme paints
; their text/glyph itself and ignores SetCtlColors, so a themed group-box title
; or check-box label renders unreadable dark-on-dark. We branch on the BS_*
; style low-nibble:
;   * group box (7) + push button (0/1, i.e. Browse) -> hidden outright (the
;     frame is redundant with the description text; Browse is unwanted chrome);
;   * check box / radio (others) -> visual style stripped (SetWindowTheme "")
;     so the label honours the SetCtlColors light text.
; Shared verbatim between installer and uninstaller via a macro; labels are
; function-scoped so reuse is safe.
!macro BXP_DARK_PAGE_BODY
    Push $0    ; current inner dialog
    Push $1    ; child iterator (previous)
    Push $2    ; current child
    Push $3    ; class name / style / temp
    Push $4    ; temp (struct ptr)
    Push $5
    Push $6
    Push $7
    Push $8
    Push $9
    Push $R0   ; captured path-edit hwnd (per dialog)
    Push $R1   ; 1 once the Browse button has been removed (per dialog)
    Push $R2   ; inner-dialog iterator (previous)
    ; Process EVERY inner dialog (#32770 child of the wizard window), not just
    ; the first. The standard pages (Directory/InstFiles) reuse one inner dialog,
    ; but the Welcome/Finish pages build their OWN — taking only the first match
    ; left the Finish check-box label dark. Visibility can't be the filter: the
    ; SHOW hook fires before the dialog is shown (IsWindowVisible == 0), which is
    ; what just turned the interior light. Colouring all of them is harmless.
    StrCpy $R2 0
  bxpdark_nextdlg:
    System::Call "user32::FindWindowEx(p $HWNDPARENT, p R2, t '#32770', p 0) p .r0"
    StrCmp $0 0 bxpdark_alldone
    StrCpy $R2 $0
    StrCpy $R0 0
    StrCpy $R1 0
    SetCtlColors $0 "EDEDED" "1E1E1E"
    StrCpy $1 0
  bxpdark_loop:
    System::Call "user32::FindWindowEx(p r0, p r1, p 0, p 0) p .r2"
    StrCmp $2 0 bxpdark_resize
    StrCpy $1 $2                                  ; advance iterator up front
    System::Call "user32::GetClassNameW(p r2, w .r3, i 32)"
    StrCmp $3 "Edit"   bxpdark_isedit
    StrCmp $3 "Button" bxpdark_isbutton
    ; Static labels, the details listbox: readable light-on-dark. Classic 3D
    ; borders / scrollbars stay system-light — darkening those needs the
    ; undocumented Win10 dark-mode opt-in, which makes themed controls ignore
    ; these colours and render unreadable dark-on-dark text, so it is not used.
    SetCtlColors $2 "EDEDED" "1E1E1E"
    Goto bxpdark_loop
  bxpdark_isedit:
    StrCpy $R0 $2                                 ; remember to widen it later
    SetCtlColors $2 "EDEDED" "1E1E1E"
    Goto bxpdark_loop
  bxpdark_isbutton:
    ; BUTTON-class text/glyph is theme-painted and ignores SetCtlColors, so a
    ; themed group-box title / check-box label renders dark-on-dark. Branch on
    ; the BS_* type in the style low-nibble.
    System::Call "user32::GetWindowLongW(p r2, i -16) i .r3"
    IntOp $3 $3 & 15
    IntCmp $3 7 bxpdark_hidegrp                   ; BS_GROUPBOX   (Dest. Folder)
    IntCmp $3 0 bxpdark_hidebtn                   ; BS_PUSHBUTTON (Browse)
    IntCmp $3 1 bxpdark_hidebtn                   ; BS_DEFPUSHBUTTON
    ; check box / radio: strip the visual style so the label takes our colours.
    System::Call 'uxtheme::SetWindowTheme(p r2, w "", w "")'
    SetCtlColors $2 "EDEDED" "1E1E1E"
    Goto bxpdark_loop
  bxpdark_hidebtn:
    StrCpy $R1 1                                  ; Browse gone -> widen the edit
    System::Call "user32::ShowWindow(p r2, i 0)"
    Goto bxpdark_loop
  bxpdark_hidegrp:
    System::Call "user32::ShowWindow(p r2, i 0)"
    Goto bxpdark_loop
  bxpdark_resize:
    ; Stretch the path edit into the space the removed Browse button vacated:
    ; keep its left/top, extend the width to a right margin matching the left.
    StrCmp $R0 0 bxpdark_dlgdone
    StrCmp $R1 0 bxpdark_dlgdone
    System::Call "*(i,i,i,i)p.r4"                 ; scratch RECT
    System::Call "user32::GetClientRect(p r0, p r4)"
    System::Call "*$4(i, i, i .r5, i)"            ; $5 = dialog client width
    System::Call "user32::GetWindowRect(p r0, p r4)"
    System::Call "*$4(i .r6, i, i, i)"            ; $6 = dialog screen-left
    System::Call "user32::GetWindowRect(p R0, p r4)"
    System::Call "*$4(i .r7, i .r8, i, i .r9)"    ; $7 left $8 top $9 bottom (screen)
    System::Free $4
    IntOp $7 $7 - $6                              ; edit left in client coords
    IntOp $9 $9 - $8                              ; edit height
    IntOp $5 $5 - $7                              ; width = clientW - leftMargin
    IntOp $5 $5 - $7                              ;        - matching rightMargin
    System::Call "user32::SetWindowPos(p R0, p 0, i 0, i 0, i r5, i r9, i 0x6)"
  bxpdark_dlgdone:
    ; Repaint this dialog, then move on to the next inner dialog.
    System::Call "user32::InvalidateRect(p r0, p 0, i 1)"
    Goto bxpdark_nextdlg
  bxpdark_alldone:
    Pop $R2
    Pop $R1
    Pop $R0
    Pop $9
    Pop $8
    Pop $7
    Pop $6
    Pop $5
    Pop $4
    Pop $3
    Pop $2
    Pop $1
    Pop $0
!macroend

Function BxpDarkPage
    !insertmacro BXP_DARK_PAGE_BODY
FunctionEnd

Function un.BxpDarkPage
    !insertmacro BXP_DARK_PAGE_BODY
FunctionEnd
!endif

; ── Install / Uninstall sections ─────────────────────────────────────────

Section "Install"
    SetOutPath "$INSTDIR"

    ; Self-heal for a same-directory update (per-user 0.2.5 → 0.2.6+): the
    ; silent updater launches us while the old bxp-gui.exe + its loaded DLLs
    ; are still running, and Windows forbids OVERWRITING a running exe / loaded
    ; DLL. It does, however, permit RENAMING one — the old process keeps running
    ; from the renamed handle. So move the locked binaries aside before File /r
    ; writes fresh copies into the vacated slots. (No-op on a fresh install:
    ; nothing to rename.) Clean any stale *.old from a prior update first.
    Delete "$INSTDIR\bxp-gui.exe.old"
    IfFileExists "$INSTDIR\bxp-gui.exe" 0 +2
        Rename "$INSTDIR\bxp-gui.exe" "$INSTDIR\bxp-gui.exe.old"
    Delete "$INSTDIR\flutter_windows.dll.old"
    IfFileExists "$INSTDIR\flutter_windows.dll" 0 +2
        Rename "$INSTDIR\flutter_windows.dll" "$INSTDIR\flutter_windows.dll.old"
    Delete "$INSTDIR\bxp-gui-bridge.dll.old"
    IfFileExists "$INSTDIR\bxp-gui-bridge.dll" 0 +2
        Rename "$INSTDIR\bxp-gui-bridge.dll" "$INSTDIR\bxp-gui-bridge.dll.old"

    File /r "${STAGEDIR}\*.*"

    ; Best-effort removal of the swapped-aside binaries. They are still locked
    ; by the exiting old process now, so /REBOOTOK schedules removal at reboot;
    ; the relaunched new app also deletes leftover *.old on startup.
    Delete /REBOOTOK "$INSTDIR\bxp-gui.exe.old"
    Delete /REBOOTOK "$INSTDIR\flutter_windows.dll.old"
    Delete /REBOOTOK "$INSTDIR\bxp-gui-bridge.dll.old"

    ; Start menu + uninstall registry
    CreateDirectory "$SMPROGRAMS\${APPNAME}"
    CreateShortCut "$SMPROGRAMS\${APPNAME}\${APPNAME}.lnk" \
        "$INSTDIR\bxp-gui.exe"
    CreateShortCut "$SMPROGRAMS\${APPNAME}\Uninstall.lnk" \
        "$INSTDIR\Uninstall.exe"

    WriteUninstaller "$INSTDIR\Uninstall.exe"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" \
        "DisplayName" "${APPNAME}"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" \
        "UninstallString" "$\"$INSTDIR\Uninstall.exe$\""
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" \
        "DisplayVersion" "${APPVERSION}"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" \
        "Publisher" "${COMPANYNAME}"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" \
        "InstallLocation" "$INSTDIR"

    ; Migration note (admin → per-user). A user upgrading from a pre-0.2.5
    ; admin install in $PROGRAMFILES64\bxp-gui can't have that copy removed
    ; from here: this installer runs non-elevated, so it cannot touch Program
    ; Files or the HKLM uninstall key. The new per-user install supersedes it
    ; (shortcut + HKCU entry point here); the old copy is left orphaned. That
    ; is acceptable for now (user base ~0); full cleanup would need a one-time
    ; elevation and is deferred. The current-user Start-Menu shortcut above is
    ; written to the same $SMPROGRAMS\${APPNAME} path the old installer used,
    ; so it is overwritten to point at the new location.

    ; Silent-install relaunch hook — UpdaterService runs setup.exe with /S
    ; and exits the running app. After install we relaunch the GUI so the
    ; user sees the new version come up automatically. The MUI2 Finish
    ; page's MUI_FINISHPAGE_RUN handles the interactive case; this branch
    ; covers the silent path that skips the wizard.
    IfSilent 0 +2
        Exec '"$INSTDIR\bxp-gui.exe"'
SectionEnd

Section "Uninstall"
    Delete "$SMPROGRAMS\${APPNAME}\${APPNAME}.lnk"
    Delete "$SMPROGRAMS\${APPNAME}\Uninstall.lnk"
    RMDir "$SMPROGRAMS\${APPNAME}"

    DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}"

    RMDir /r "$INSTDIR"
SectionEnd
