// Generates bxp-gui's reference Markdown pages from its Dart `*Doc` catalogs:
//
//   GuiToolDoc  (gui_mcp_server.dart)  → gui-agent-tools.md
//   ShortcutDoc (platform_shortcuts.dart) → gui-shortcuts.md
//   PrefDoc     (prefs_service.dart)   → gui-prefs.md
//
// Runs as a `flutter test` (not `dart run`): importing bxp_gui links dart:ui via
// Flutter, which only the Flutter test engine provides. The "test" never asserts
// behaviour — it materialises each catalog and writes the page; the throwaway
// build is the point.
//
// GuiToolDoc is built per server instance (each tool callback closes over server
// state), so we construct a GuiMcpServer with a stub host and read it via
// `toolCatalogForDocs()`; the callbacks are never invoked. ShortcutDoc / PrefDoc
// are a plain function / static const, read directly.
//
// Output root: BXP_DOCS_OUT env (scripts/docs/gen-docs.sh sets it), else ../../docs.
// Pages are written under it by their site-relative path, so the drift guard
// can diff a whole generated tree against the committed one.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:bxp_gui/services/gui_mcp_server.dart';
import 'package:bxp_gui/services/prefs_service.dart';
import 'package:bxp_gui/ui/platform_shortcuts.dart';

class _StubHost implements GuiMcpHost {
  @override
  dynamic noSuchMethod(Invocation invocation) => throw UnimplementedError();
}

String _cell(String s) => s.replaceAll('|', r'\|').replaceAll('\n', ' ');

// HTML-escape a value for a raw inline `<code>` cell (guards the table pipe and
// HTML metacharacters), then wrap it in a coloured code span. The class is bound
// by the stylesheet to the active theme's --md-code-hl-* token colour, matching
// the Zig-generated reference pages.
String _htmlEsc(String s) => s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('|', '&#124;');
String _code(String s, String cls) => '<code class="$cls">${_htmlEsc(s)}</code>';

void _writePage(
  String dir,
  String file,
  String title,
  String source,
  String intro,
  List<String> headers,
  List<List<String>> rows,
) {
  final out = StringBuffer()
    // Front matter: Material renders `description` as the page's
    // <meta name="description">, and scripts/docs/gen-trees.py reads it as the
    // page's blurb. The intro sentence already says what the page is, so it is
    // reused rather than written twice.
    ..writeln('---')
    ..writeln('description: "$intro"')
    ..writeln('---')
    ..writeln()
    ..writeln('# $title')
    ..writeln()
    ..writeln('<!-- GENERATED by tools/dart-doc-gen from $source. Do not edit. -->')
    ..writeln()
    ..writeln(intro)
    ..writeln()
    ..writeln('| ${headers.join(' | ')} |')
    ..writeln('| ${headers.map((_) => '---').join(' | ')} |');
  for (final r in rows) {
    out.writeln('| ${r.map(_cell).join(' | ')} |');
  }
  final path = '$dir/reference/$file';
  File(path).parent.createSync(recursive: true);
  File(path).writeAsStringSync(out.toString());
  stdout.writeln('dart-doc-gen: wrote $path');
}

void main() {
  test('generate bxp-gui reference pages', () {
    final dir = Platform.environment['BXP_DOCS_OUT'] ?? '../../docs';

    // gui-agent-tools — needs a server instance (closures); stub host suffices.
    final server = GuiMcpServer(_StubHost(), confirm: (_, _) async => false);
    _writePage(
      dir,
      'gui-agent-tools.md',
      'GUI agent tools (gui-mcp)',
      'GuiToolDoc',
      'Agent-callable tools the running bxp-gui exposes over localhost StreamableHTTP.',
      ['Tool', 'What it does'],
      [for (final t in server.toolCatalogForDocs()) [_code(t.name, 'hl-fn'), t.description]],
    );

    // gui-shortcuts — shortcutCatalog() is a plain platform-aware function.
    _writePage(
      dir,
      'gui-shortcuts.md',
      'Keyboard shortcuts',
      'ShortcutDoc',
      'BXP Desktop keyboard shortcuts (modifier shown for this platform).',
      ['Action', 'Shortcut'],
      [for (final s in shortcutCatalog()) [s.action, _code(s.keys, 'hl-type')]],
    );

    // gui-prefs — Prefs.all is a static const catalog.
    _writePage(
      dir,
      'gui-prefs.md',
      'User preferences',
      'PrefDoc',
      'Keys persisted in the bxp-gui preferences file (see the GUI guide for the file path).',
      ['Key', 'Description'],
      [for (final p in Prefs.all) [_code(p.key, 'hl-key'), p.description]],
    );
  });
}
